# configs/cityscapes.yaml
dataset:
  root_dir: "/content/datasets/cityscapes"
  num_classes: 19
  ignore_index: 255

training:
  batch_size: 8
  epochs: 20
  learning_rate: 0.0001
  
transforms:
  image_height: 256
  image_width: 512

# Classes (Cityscapes 19 evaluation classes)
names:
  0: road
  1: sidewalk
  2: building
  3: wall
  4: fence
  5: pole
  6: traffic light
  7: traffic sign
  8: vegetation
  9: terrain
  10: sky
  11: person
  12: rider
  13: car
  14: truck
  15: bus
  16: train
  17: motorcycle
  18: bicycle